### ISSUE TITLE
Join Wahoo?

### ISSUE THREAD

**Issue by ghost** [techwizrd/fishmarks#14]
We are still relatively new in town, and just getting started, but we are more stable than the other options, namely OMF. I think some of these functions could be turned into a handful of Wahoo plugins or maybe some could be even make it to core. We are always accepting feature request and feedback. I would love if you could give [Wahoo](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) a look.

Regards :smile:

**Comment by techwizrd** [comment]
Perhaps. I'll look into it, unless you'd like to submit a pull request.

**Comment by bucaran** [comment]
I'll look into coming with a PR for this. Thanks for taking the time :+1:

**Comment by techwizrd** [comment]
Are you still interested in adding a PR for this to add fishmarks to Fisherman?
