### ISSUE TITLE
Strange bug when using fishmarks

### ISSUE THREAD

**Issue by Immortalin** [techwizrd/fishmarks#16]
Hi, I am not sure whether this is a bug or a feature. I use GNU stow and git to manage my dotfiles on multiple ubuntu machines so fishmarks' `.sdirs` file is always symlinked from my dotfiles git repo to the home directory. However, the `.sdirs` symlink is sometimes no longer effective and fishmarks starts reading from a non-symlinked `.sdirs=` file it created, causing me to always have to copy the new file into my dotfiles git repo, rename it, and symlink it again. This behaviour is highly annoying but I have no idea what are the conditions that cause it as it seems to appear randomly whenever I add a new bookmark.

**Comment by techwizrd** [comment]
When adding a bookmark, if an `.sdirs` file does not exist (or is not writable), it creates one and starts writing to it.

**Comment by Immortalin** [comment]
@techwizrd so it's basically a race condition?
