### ISSUE TITLE
Remove automatic way of installing

### ISSUE THREAD

**Issue by rkrueger11** [techwizrd/fishmarks#18]
As noted, this way is _terrible_ for security.  Let's not even list it as an option.  The manual way is not difficult.  Or find a more secure way of doing it "automatically".

**Comment by techwizrd** [comment]
There's a notice specifically about this in the `README.md` directly after the command for automatic installation where I explain why it's not recommended. However, it's a feature people like (especially those not using a package manager).

> Please note, however, that you should never install things by piping untrusted "install" scripts downloaded through curl directly into your shell (be it bash or fish). Even if you read through the install script and think you understand it, you could be prone to a man-in-the-middle attack or any number of security vulnerabilities. While manual installations are tedious, they are recommended for any situations where security is a concern (and it should almost always be a concern).

If you have a more secure way of doing automatically (perhaps a local hash check), I'd be willing to include that as a PR.
