### ISSUE TITLE
Automatic installation fails with an error

### ISSUE THREAD

**Issue by fedorpashin** [techwizrd/fishmarks#21]
The error is:

> Expected a string, but instead found a pipe

https://github.com/techwizrd/fishmarks/blob/485f6b3c258a8279ffee1991a290616e5b01005f/install.fish#L3

**Comment by techwizrd** [comment]
Can you give me some more details regarding your system? What operating system and shell are you using?

**Comment by fedorpashin** [comment]
I use macOS 10.15.7 and fish shell.

**Comment by blissdev** [comment]
Received this error on macOS 11.1 Beta and fish 3.1.2 as well.

**Comment by glenpadua** [comment]
Facing this issue as well on macOS 11.2
